# Words List

words = (
    "apple", "orange", "banana", "coconut", "pineapple", "mango", "strawberry", "blueberry", "raspberry", "watermelon",
    "cherry", "lemon", "lime", "avocado", "peach", "apricot", "plum", "kiwi", "grape", "papaya", "tomato",
    "cucumber", "potato", "onion", "garlic", "pepper", "carrot", "lettuce", "spinach", "broccoli", "cabbage",
    "mushroom", "zucchini", "eggplant", "pumpkin", "radish", "asparagus", "celery", "parsley", "basil", "coriander",
    "bread", "butter", "cheese", "yogurt", "milk", "coffee", "tea", "chocolate", "honey", "sugar",
    "salt", "vinegar", "mustard", "ketchup", "mayonnaise", "rice", "pasta", "noodles", "flour", "corn",
    "chicken", "beef", "pork", "turkey", "lamb", "fish", "shrimp", "crab", "lobster", "salmon",
    "shark", "dolphin", "whale", "octopus", "turtle", "jellyfish", "seahorse", "penguin", "eagle", "owl",
    "lion", "tiger", "elephant", "giraffe", "zebra", "monkey", "gorilla", "panda", "kangaroo", "cheetah",
    "rabbit", "squirrel", "fox", "wolf", "bear", "deer", "moose", "raccoon", "skunk", "hedgehog",
    "sun", "moon", "stars", "planet", "galaxy", "comet", "asteroid", "nebula", "blackhole", "satellite",
    "ocean", "river", "lake", "waterfall", "stream", "pond", "glacier", "iceberg", "wave", "tide",
    "mountain", "hill", "valley", "plateau", "canyon", "desert", "forest", "jungle", "savanna", "grassland",
    "volcano", "earthquake", "tsunami", "hurricane", "tornado", "thunderstorm", "lightning", "rain", "snow", "hail",
    "cloud", "fog", "mist", "breeze", "wind", "cyclone", "monsoon", "drought", "flood", "avalanche",
    "computer", "laptop", "tablet", "smartphone", "keyboard", "mouse", "monitor", "printer", "router", "modem",
    "software", "hardware", "internet", "website", "database", "algorithm", "encryption", "cybersecurity", "network", "server",
    "programming", "coding", "debugging", "compiler", "binary", "variable", "function", "loop", "array", "string",
    "artificial", "intelligence", "machine", "learning", "neural", "network", "automation", "robotics", "sensor", "processor",
    "science", "physics", "chemistry", "biology", "astronomy", "geology", "meteorology", "ecology", "genetics", "evolution",
    "medicine", "pharmacy", "surgery", "vaccine", "antibiotic", "microbiology", "radiology", "immunology", "pathology", "diagnosis",
    "doctor", "nurse", "dentist", "therapist", "psychiatrist", "psychologist", "surgeon", "optometrist", "cardiologist", "neurologist",
    "teacher", "professor", "student", "school", "university", "library", "homework", "exam", "research", "lecture",
    "history", "geography", "economics", "politics", "sociology", "philosophy", "literature", "linguistics", "psychology", "anthropology",
    "music", "guitar", "piano", "violin", "drums", "flute", "saxophone", "orchestra", "concert", "singer",
    "painting", "sculpture", "drawing", "sketching", "calligraphy", "photography", "cinema", "theater", "opera", "ballet",
    "sports", "football", "basketball", "tennis", "cricket", "baseball", "hockey", "volleyball", "swimming", "running",
    "cycling", "skating", "skiing", "snowboarding", "surfing", "boxing", "wrestling", "karate", "taekwondo", "fencing",
    "car", "truck", "bus", "train", "airplane", "helicopter", "boat", "submarine", "bicycle", "motorcycle",
    "road", "highway", "bridge", "tunnel", "airport", "harbor", "station", "platform", "garage", "parking",
    "house", "apartment", "villa", "bungalow", "mansion", "cottage", "tent", "skyscraper", "castle", "palace",
    "furniture", "sofa", "table", "chair", "bed", "wardrobe", "shelf", "cabinet", "mirror", "lamp",
    "kitchen", "oven", "stove", "microwave", "refrigerator", "toaster", "blender", "dishwasher", "sink", "faucet",
    "bathroom", "toilet", "shower", "bathtub", "towel", "mirror", "soap", "shampoo", "toothpaste", "toothbrush",
    "clothing", "shirt", "pants", "jacket", "sweater", "jeans", "shorts", "dress", "skirt", "scarf",
    "shoes", "sneakers", "sandals", "boots", "slippers", "heels", "hat", "cap", "gloves", "belt",
    "time", "clock", "watch", "calendar", "schedule", "alarm", "deadline", "appointment", "meeting", "conference",
    "money", "bank", "credit", "debit", "wallet", "currency", "salary", "investment", "loan", "budget",
    "government", "law", "court", "judge", "lawyer", "police", "prison", "election", "democracy", "republic",
    "holiday", "vacation", "festival", "celebration", "birthday", "wedding", "anniversary", "party", "fireworks", "parade",
    "happiness", "sadness", "anger", "love", "fear", "surprise", "disgust", "pride", "hope", "peace"
)
